######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 3 14:22:15 2020
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += gui
QT += widgets

# Input
SOURCES += HelloWorldExample.cpp
